# Generated by Django 4.2.10 on 2024-02-28 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(verbose_name='временная метка')),
                ('download_bandwidth', models.PositiveBigIntegerField(verbose_name='загрузка')),
                ('download_bytes', models.PositiveBigIntegerField(verbose_name='загружено байт')),
                ('download_elapsed', models.PositiveBigIntegerField(verbose_name='время затраченное на загрузку')),
                ('upload_bandwidth', models.PositiveBigIntegerField(verbose_name='выгрузка')),
                ('upload_bytes', models.PositiveBigIntegerField(verbose_name='выгружено байт')),
                ('upload_elapsed', models.PositiveBigIntegerField(verbose_name='время затраченное на выгрузку')),
                ('ping_jitter', models.FloatField(verbose_name='jitter')),
                ('ping_latency', models.FloatField(verbose_name='latency')),
                ('ping_high', models.FloatField(verbose_name='high')),
                ('ping_low', models.FloatField(verbose_name='low')),
            ],
            options={
                'verbose_name': 'Результат',
                'verbose_name_plural': 'Результаты',
            },
        ),
    ]
