# Generated by Django 4.2.10 on 2024-02-26 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Download',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('jitter', models.FloatField()),
                ('low', models.FloatField()),
                ('high', models.FloatField()),
                ('imq', models.FloatField()),
                ('bandwidth', models.BigIntegerField()),
                ('bytes', models.BigIntegerField()),
                ('elapses', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Ping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('jitter', models.FloatField()),
                ('low', models.FloatField()),
                ('high', models.FloatField()),
                ('latency', models.FloatField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('jitter', models.FloatField()),
                ('low', models.FloatField()),
                ('high', models.FloatField()),
                ('imq', models.FloatField()),
                ('bandwidth', models.BigIntegerField()),
                ('bytes', models.BigIntegerField()),
                ('elapses', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
