# Generated by Django 4.2.10 on 2024-02-27 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('speedtest', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='download',
            old_name='imq',
            new_name='iqm',
        ),
        migrations.RenameField(
            model_name='upload',
            old_name='imq',
            new_name='iqm',
        ),
    ]
