# Generated by Django 4.2.10 on 2024-02-27 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('speedtest', '0002_rename_imq_download_iqm_rename_imq_upload_iqm'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpeedTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('download', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='speedtest.download')),
                ('ping', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='speedtest.ping')),
                ('upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='speedtest.upload')),
            ],
        ),
    ]
